### ISSUE TITLE
Drop events without a date when date slider used

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Mapping-Timelines-Project#7]

**Comment by robinetmiller** [comment]
This needs a little clarification. Is this a request to specifically not plot on the map if there is no date information?

**Comment by ilovan** [comment]
Yes. In this case, the date slider acts as a filtering option (just like any of the facets) so only the items that meet the specified criterion should be displayed in any of the two visualizations.

**Comment by robinetmiller** [comment]
This function appears to already work. I have a test file with three events. A and B have dates, while C has none. Using the date slider at all will remove pin C. Source: https://gist.github.com/robinetmiller/ce5f1d7216de838e5b15

I do notice there are some elements that seem to not obey this behaviour, but upon examination, all of these have bogus data (eg. "p111") in their date field, which the tool parses as a year (111AD). Is there still the desire to have it handle those kinds of bogus entries better, or is this to be considered a data problem and the ticket closed?

**Comment by SusanBrown** [comment]
We don’t want to try to modify the tool to fix these sorts of problems in the data. 

Michael, do you think perhaps we could modify the event schemas to eliminate some of these problems by limiting the values of dates to numerical characters?

**Comment by brundin** [comment]
I agree: this is a data integrity issue, and we should not modify the application to address problems in the data.

The CWRC/Orlando, MODS, and TEI schemas all have date-related attributes in date elements in their respective event container elements that must contain ISO 8601 format values (well, the Orlando dates use a slight variant of this ISO standard, but they do follow a consistent format).  The Plot-It properties of startDate and endDate require the value in the key-value pair to be an ISO 8601 format.  The problem, obviously, is if in the encoded markup for an event the date value is a text node value in the date element that is not in this format, e.g., "June 4, 2001".

Moving forward, Jeff has done an amazing job in his XQuery scripts that transform XML events into Plot-It JSON items by creating a variety of conditional checks whose function is to try and normalize dates and disambiguate and geocode places, in cases where the dates do not use formatted attribute values and the places do not have REF (i.e., a GeoNames URI), LAT, or LONG values.  So for dates, for example, in the existing Orlando corpus of freestanding events, if a date in the DATE element text node appeared as "12 July 1884", the formatted VALUE attribute typically would not be used; Jeff's code normalizes this date value so that the "12 July 1884" value is converted into the JSON startDate value of "1884-07-12", which can then be rendered correctly on the Plot-It timeline.

**Comment by SusanBrown** [comment]
Thanks for the explanation, Michael. Then I think that we’ve already done a lot to ensure that dates are correct and we should simply have a troubleshooting section in the documentation for when events don’t plot on either the map or the timeline.
